//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> telefono { get; set; }
        public string direccion { get; set; }
        public string empresa { get; set; }
        public string departamento { get; set; }
    }
}
